project:
  type: book
  output-dir: _site

book:
  title: "Microbiology of Extreme Environments"
  author: "Donato Giovannelli"

  cover-image: book/figures/book_cover.png
  cover-image-alt: "Cover of Microbiology of Extreme Environments"

  repo-url: https://github.com/giovannellilab/Extreme_microbiology_book
  repo-actions: [edit, issue]
  downloads: [pdf, epub]

  chapters:
    - index.md
    - book/18_psychrophiles.md
    - book/19_thermophiles_and_hyperthermophiles.md
    - book/references.md
    - book/changelog.md
    - book/credits.md

bibliography: references/bibliography.bib
csl: references/nature.csl

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo

  pdf:
    documentclass: book
    toc: true
    number-sections: true

  epub:
    toc: true

execute:
  enabled: false